services:
  octane:
    image: simple-order-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: ["/app/entrypoint.sh"]
    command: ["/bin/sh", "-c", "php /app/artisan octane:frankenphp --watch"]
    restart: unless-stopped